// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gemba/rewardstreamer/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params configures the rewardstreamer stream.
type Params struct {
	Enabled       bool                  `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	RewardDenom   string                `protobuf:"bytes,2,opt,name=reward_denom,json=rewardDenom,proto3" json:"reward_denom,omitempty"`
	AnnualReward  cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=annual_reward,json=annualReward,proto3,customtype=cosmossdk.io/math.Int" json:"annual_reward"`
	BlocksPerYear uint64                `protobuf:"varint,4,opt,name=blocks_per_year,json=blocksPerYear,proto3" json:"blocks_per_year,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_70bb300d67034ee3, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Params) GetRewardDenom() string {
	if m != nil {
		return m.RewardDenom
	}
	return ""
}

func (m *Params) GetBlocksPerYear() uint64 {
	if m != nil {
		return m.BlocksPerYear
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "gemba.rewardstreamer.v1.Params")
}

func init() {
	proto.RegisterFile("gemba/rewardstreamer/v1/params.proto", fileDescriptor_70bb300d67034ee3)
}

var fileDescriptor_70bb300d67034ee3 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x41, 0x4b, 0xeb, 0x40,
	0x10, 0x80, 0xb3, 0xef, 0x95, 0xbe, 0xf7, 0xf6, 0xb5, 0x88, 0x41, 0x31, 0xf6, 0x90, 0x56, 0x11,
	0x29, 0x82, 0x59, 0x8b, 0xff, 0xa0, 0x0a, 0xd2, 0x5b, 0x09, 0x78, 0x50, 0x90, 0x30, 0x49, 0x96,
	0x34, 0x34, 0xbb, 0x1b, 0x76, 0xb7, 0xd1, 0xfe, 0x0b, 0x7f, 0x86, 0x47, 0x0f, 0xfe, 0x04, 0x0f,
	0x3d, 0x16, 0x4f, 0xe2, 0xa1, 0x48, 0x7b, 0xf0, 0x6f, 0x48, 0xb2, 0xf5, 0xa0, 0x97, 0x61, 0xe7,
	0x9b, 0x8f, 0x99, 0x61, 0x16, 0x1f, 0x24, 0x94, 0x85, 0x40, 0x24, 0xbd, 0x05, 0x19, 0x2b, 0x2d,
	0x29, 0x30, 0x2a, 0x49, 0xd1, 0x23, 0x39, 0x48, 0x60, 0xca, 0xcb, 0xa5, 0xd0, 0xc2, 0xde, 0xa9,
	0x2c, 0xef, 0xbb, 0xe5, 0x15, 0xbd, 0xd6, 0x56, 0x22, 0x12, 0x51, 0x39, 0xa4, 0x7c, 0x19, 0xbd,
	0xb5, 0x1b, 0x09, 0xc5, 0x84, 0x0a, 0x4c, 0xc1, 0x24, 0xeb, 0xd2, 0x26, 0xb0, 0x94, 0x0b, 0x52,
	0x45, 0x83, 0xf6, 0x9f, 0x11, 0xae, 0x0f, 0xab, 0x69, 0xb6, 0x83, 0xff, 0x50, 0x0e, 0x61, 0x46,
	0x63, 0x07, 0x75, 0x50, 0xf7, 0xaf, 0xff, 0x95, 0xda, 0x7b, 0xb8, 0x61, 0xa6, 0x07, 0x31, 0xe5,
	0x82, 0x39, 0xbf, 0x3a, 0xa8, 0xfb, 0xcf, 0xff, 0x6f, 0xd8, 0x79, 0x89, 0xec, 0x4b, 0xdc, 0x04,
	0xce, 0x27, 0x90, 0x05, 0x86, 0x3a, 0xbf, 0x4b, 0xa7, 0x7f, 0x32, 0x5b, 0xb4, 0xad, 0xb7, 0x45,
	0x7b, 0xdb, 0xec, 0xa1, 0xe2, 0xb1, 0x97, 0x0a, 0xc2, 0x40, 0x8f, 0xbc, 0x01, 0xd7, 0x2f, 0x4f,
	0xc7, 0x78, 0xbd, 0xe0, 0x80, 0xeb, 0x87, 0x8f, 0xc7, 0x23, 0xe4, 0x37, 0x4c, 0x1b, 0xbf, 0xea,
	0x62, 0x1f, 0xe2, 0x8d, 0x30, 0x13, 0xd1, 0x58, 0x05, 0x39, 0x95, 0xc1, 0x94, 0x82, 0x74, 0x6a,
	0x1d, 0xd4, 0xad, 0xf9, 0x4d, 0x83, 0x87, 0x54, 0x5e, 0x51, 0x90, 0xfd, 0x9b, 0xd9, 0xd2, 0x45,
	0xf3, 0xa5, 0x8b, 0xde, 0x97, 0x2e, 0xba, 0x5f, 0xb9, 0xd6, 0x7c, 0xe5, 0x5a, 0xaf, 0x2b, 0xd7,
	0xba, 0x3e, 0x4b, 0x52, 0x3d, 0x9a, 0x84, 0x5e, 0x24, 0x18, 0x49, 0x0b, 0xe0, 0xa2, 0x50, 0x19,
	0x14, 0x53, 0x72, 0x51, 0x1e, 0xb5, 0x5f, 0x36, 0x89, 0x46, 0x90, 0x72, 0x62, 0xe2, 0xdd, 0xcf,
	0xcf, 0xd0, 0xd3, 0x9c, 0xaa, 0xb0, 0x5e, 0x1d, 0xeb, 0xf4, 0x33, 0x00, 0x00, 0xff, 0xff, 0x77,
	0xa4, 0x9b, 0xcb, 0xb1, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlocksPerYear != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BlocksPerYear))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.AnnualReward.Size()
		i -= size
		if _, err := m.AnnualReward.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.RewardDenom) > 0 {
		i -= len(m.RewardDenom)
		copy(dAtA[i:], m.RewardDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.RewardDenom)))
		i--
		dAtA[i] = 0x12
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Enabled {
		n += 2
	}
	l = len(m.RewardDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.AnnualReward.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.BlocksPerYear != 0 {
		n += 1 + sovParams(uint64(m.BlocksPerYear))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnnualReward", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AnnualReward.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlocksPerYear", wireType)
			}
			m.BlocksPerYear = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlocksPerYear |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
