// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gemba/feesplit/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params configures the fee split (CLAUDE.md §5.4: 40% faucet / 60% validators).
type Params struct {
	Enabled        bool                        `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	FaucetFeeRatio cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=faucet_fee_ratio,json=faucetFeeRatio,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"faucet_fee_ratio"`
	FaucetAccount  string                      `protobuf:"bytes,3,opt,name=faucet_account,json=faucetAccount,proto3" json:"faucet_account,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_465a0caa85df8844, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Params) GetFaucetAccount() string {
	if m != nil {
		return m.FaucetAccount
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "gemba.feesplit.v1.Params")
}

func init() { proto.RegisterFile("gemba/feesplit/v1/params.proto", fileDescriptor_465a0caa85df8844) }

var fileDescriptor_465a0caa85df8844 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xc1, 0x4a, 0xf3, 0x40,
	0x14, 0x85, 0x33, 0xff, 0x0f, 0x55, 0x03, 0x8a, 0x0d, 0x2e, 0x62, 0x85, 0xb4, 0x08, 0x42, 0x11,
	0xcc, 0x50, 0x04, 0x77, 0x2e, 0x2c, 0x45, 0x37, 0x2e, 0x24, 0x1b, 0xc1, 0x4d, 0xbc, 0x99, 0xde,
	0xa6, 0x43, 0x93, 0xdc, 0xd0, 0x99, 0x06, 0xfb, 0x16, 0x3e, 0x86, 0xe0, 0xc6, 0x85, 0x0f, 0xd1,
	0x65, 0x71, 0x25, 0x2e, 0x8a, 0xb4, 0x0b, 0x5f, 0x43, 0x92, 0x69, 0x71, 0x73, 0x99, 0x7b, 0xbe,
	0xe1, 0x9c, 0xcb, 0xb1, 0xbd, 0x18, 0xd3, 0x08, 0xf8, 0x00, 0x51, 0xe5, 0x89, 0xd4, 0xbc, 0xe8,
	0xf0, 0x1c, 0xc6, 0x90, 0x2a, 0x3f, 0x1f, 0x93, 0x26, 0xa7, 0x5e, 0x71, 0x7f, 0xc3, 0xfd, 0xa2,
	0xd3, 0x38, 0x88, 0x29, 0xa6, 0x8a, 0xf2, 0xf2, 0x65, 0x3e, 0x36, 0x0e, 0x05, 0xa9, 0x94, 0x54,
	0x68, 0x80, 0x59, 0xd6, 0xa8, 0x0e, 0xa9, 0xcc, 0x88, 0x57, 0xd3, 0x48, 0xc7, 0xaf, 0xcc, 0xae,
	0xdd, 0x55, 0x39, 0x8e, 0x6b, 0x6f, 0x61, 0x06, 0x51, 0x82, 0x7d, 0x97, 0xb5, 0x58, 0x7b, 0x3b,
	0xd8, 0xac, 0xce, 0xa3, 0xbd, 0x3f, 0x80, 0x89, 0x40, 0x1d, 0x0e, 0x10, 0xc3, 0x31, 0x68, 0x49,
	0xee, 0xbf, 0x16, 0x6b, 0xef, 0x74, 0x2f, 0x66, 0x8b, 0xa6, 0xf5, 0xb5, 0x68, 0x1e, 0x99, 0x1c,
	0xd5, 0x1f, 0xf9, 0x92, 0x78, 0x0a, 0x7a, 0xe8, 0xdf, 0x62, 0x0c, 0x62, 0xda, 0x43, 0xf1, 0xf1,
	0x7e, 0x66, 0xaf, 0xcf, 0xe8, 0xa1, 0x78, 0xf9, 0x79, 0x3b, 0x65, 0xc1, 0x9e, 0xf1, 0xbb, 0x46,
	0x0c, 0x4a, 0x37, 0xe7, 0xc4, 0x5e, 0x2b, 0x21, 0x08, 0x41, 0x93, 0x4c, 0xbb, 0xff, 0x4b, 0xff,
	0x60, 0xd7, 0xa8, 0x57, 0x46, 0xec, 0xde, 0xcf, 0x96, 0x1e, 0x9b, 0x2f, 0x3d, 0xf6, 0xbd, 0xf4,
	0xd8, 0xf3, 0xca, 0xb3, 0xe6, 0x2b, 0xcf, 0xfa, 0x5c, 0x79, 0xd6, 0xc3, 0x65, 0x2c, 0xf5, 0x70,
	0x12, 0xf9, 0x82, 0x52, 0x2e, 0x0b, 0xc8, 0xa8, 0x50, 0x09, 0x14, 0x53, 0x7e, 0x53, 0xb6, 0xd6,
	0x4d, 0x48, 0x8c, 0xc4, 0x10, 0x64, 0xc6, 0xcd, 0x7c, 0xfa, 0xeb, 0x59, 0x4f, 0x73, 0x54, 0x51,
	0xad, 0x6a, 0xe3, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xb3, 0xdc, 0xd1, 0x86, 0x01, 0x00,
	0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FaucetAccount) > 0 {
		i -= len(m.FaucetAccount)
		copy(dAtA[i:], m.FaucetAccount)
		i = encodeVarintParams(dAtA, i, uint64(len(m.FaucetAccount)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.FaucetFeeRatio.Size()
		i -= size
		if _, err := m.FaucetFeeRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Enabled {
		n += 2
	}
	l = m.FaucetFeeRatio.Size()
	n += 1 + l + sovParams(uint64(l))
	l = len(m.FaucetAccount)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FaucetFeeRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FaucetFeeRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FaucetAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FaucetAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
